### ISSUE TITLE
Partial location info shows weirdly

### ISSUE THREAD

**Issue by Xavdidtheshadow** [LinuxBozo/jsonresume-theme-kendall#11]
Hey there!

So in my resume, I've got the following location:

```
"location": {
      "city": "Palo Alto",
      "countryCode": "USA",
      "region": "CA"
    }
```

When the page displays, it shows `Palo Alto, USA`, all on the top row of the box (vs email, which is centered vertically). Is this expected behavior?

**Comment by LinuxBozo** [comment]
@Xavdidtheshadow There ya go. That should fix it up.

**Comment by Xavdidtheshadow** [comment]
Awesome, thanks so much!
