### ISSUE TITLE
Social profiles icon generation

### ISSUE THREAD

**Issue by paskal** [LinuxBozo/jsonresume-theme-kendall#14]
Hello!

Your theme is awesome, but I'm stuck with one issue: no matter how I name StackOverflow profile in resume.json, it generates `fa-stackoverflow-square` icon instead of `fa-stack-overflow`, could you please update that profile definitions to match more possible variants? Current  code seems not working with "stack-overflow" case for me and  stack*O*veflow with CamelCase on second word only seems counter-intuitive:

```
            case "stack-overflow":
            case "stackOverflow":
                p.iconClass = "fa fa-stack-overflow";
break;
```
I propose to include `StackOverflow`, `Stack-Overflow`, `stackoverflow`, and review other profiles as well. Also, case statement could be checked - in my setup it's somewhy not working as expected, I'll be glad to give you my environment data if you'll tell me which is relevant.

**Comment by paskal** [comment]
I've just rechecked, `stackOverflow` and `stackoverflow` in resume.json doesn't give you proper icon, only `stack-overflow` works and only with resume-cli generator, not with hackmyresume.

Also it will be nice to have a telegram icon there as well.

**Comment by LinuxBozo** [comment]
Should be fixed by https://github.com/LinuxBozo/jsonresume-theme-kendall/commit/595708ebd7898e2e8031f083aeba69f533f17768

**Comment by paskal** [comment]
@LinuxBozo, you commits are beautiful, thank you very much for quick fix.

**Comment by paskal** [comment]
I guess, unnecessary requirement to profile names should be removed from README.md:
> every field in the basics.profiles array **must** be entered lowercase, without spaces.

**Comment by LinuxBozo** [comment]
Good catch. README updated: https://github.com/LinuxBozo/jsonresume-theme-kendall/commit/bd1db6b24e8e55486afc1d1037a8cdf0d721ea14
