### ISSUE TITLE
PDF output improvement

### ISSUE THREAD

**Issue by paskal** [LinuxBozo/jsonresume-theme-kendall#15]
Hello!

If you export kendall html resume to pdf, (`xvfb-run wkhtmltopdf kendall.html kendall.pdf`) it have two issues, first, it loses avatar:
![image](https://cloud.githubusercontent.com/assets/712534/21286134/0f6e6c86-c465-11e6-8df7-c25e256d7c07.png)
And second, it have awkward line breaks:
![image](https://cloud.githubusercontent.com/assets/712534/21286137/285d8aa6-c465-11e6-84f2-096ea67d5fce.png)
I guess, avatar should be added to printed output, and some parts of content should be marked as unbreakable so they will be moved to next page on print.

**Comment by LinuxBozo** [comment]
The avatar not displaying during print is a design decision. See: https://github.com/LinuxBozo/jsonresume-theme-kendall/blob/master/print.css#L10

You are correct about awkward page breaks though. Solved in https://github.com/LinuxBozo/jsonresume-theme-kendall/commit/fcda74eb131f72df02a34a10107b74d72c752f0a

**Comment by paskal** [comment]
Hello again! I've noticed something strange with skills header when I'm printing page from Firefox 54, could you please take a look?
![image](https://user-images.githubusercontent.com/712534/26863482-84e3cb82-4b5b-11e7-8d2c-3e61975fcf5e.png)

Non-pdf:
![image](https://user-images.githubusercontent.com/712534/26863514-b30fe266-4b5b-11e7-8990-79bdfcb06215.png)

First skill from second page leaped to "skills" header.

**Comment by paskal** [comment]
Dear @LinuxBozo, current line breaks are too tough: they leave up to half of a page empty:
![image](https://user-images.githubusercontent.com/712534/33622873-248dfa9e-da00-11e7-9762-481bc5432009.png)
I suggest to apply "non-breakable" property to smaller blocks than full "job and all it's highlights" block.

**Comment by paskal** [comment]
Removing `job.` from `page-break-inside` fixes problem for me:
![image](https://user-images.githubusercontent.com/712534/33622999-9d316260-da00-11e7-8de7-b1522cc27034.png)

**Comment by paskal** [comment]
If I remove .job and .job-details from this property, I get following skills mess somewhy:
![image](https://user-images.githubusercontent.com/712534/33624141-6dd74346-da04-11e7-9c71-87c48b3380af.png)

**Comment by paskal** [comment]
@LinuxBozo, could you please take a look? I've give it a thought but can't find easy way to fix it taking what I've wrote before into account.

**Comment by LinuxBozo** [comment]
@paskal I'll see if I can get some time this week to look into this.

**Comment by LinuxBozo** [comment]
@paskal ok, should be better in d10ddbd  Have published new version.
