### ISSUE TITLE
Unable to load theme

### ISSUE THREAD

**Issue by fixl** [LinuxBozo/jsonresume-theme-kendall#18]
Not quite sure if this is the right place, but http://themes.jsonresume.org/theme/kendall returns a 504

So does running `resume serve --theme kendall`. That eventually returns `There was an error downloading your generated html resume from our server: Error: Gateway Timeout`

**Comment by paskal** [comment]
It seems to be not actual, the link from above works fine. Also, it's not served by this theme owner but rather by jsonresume.org owners themselves.

**Comment by LinuxBozo** [comment]
Closing as #wontfix since this isn't really an issue with the theme itself.
