### ISSUE TITLE
Update the version of Font Awesome to 5.x

### ISSUE THREAD

**Issue by yungshenglu** [LinuxBozo/jsonresume-theme-kendall#20]
There are some new icons in Font Awesome v5.x. However, the version of Font Awesome in this repository is still v4.7. Maybe we can update our version to v5.x?

**Comment by paskal** [comment]
Hi @yungshenglu, which particular icons that are not available in v4.7 you want to use?

**Comment by LinuxBozo** [comment]
This is done in version 0.2.0.
