### ISSUE TITLE
Add support for JSON Resume schema v1.0.0

### ISSUE THREAD

**Issue by felipecrs** [LinuxBozo/jsonresume-theme-kendall#27]
Hi @LinuxBozo,

Your theme is awesome and by far my favorite one. However, some changes were introduced by [JSON Resume schema v1.0.0](https://github.com/jsonresume/resume-schema/tree/v1.0.0) (and also new features), that are not currently supported by this theme.

I'll list some that I found:

- [ ] [Projects](https://github.com/jsonresume/resume-schema/blob/v1.0.0/schema.json#L383).

- [ ] Website got replaced with URL in `basics`, `work`, and probably more.

- [ ] URL was introduced for `education`.

I believe there is a way to implement all of these features with redundancy, so it would be possible to still support users of schema `0.0.0` and `v1.0.0`.

I see that you don't change this repository for a while, and it would be awesome to have such this update for this theme, so I wanted to know if you're considering to update.

**Comment by felipecrs** [comment]
@Wenzel could you submit a PR for [your branch](https://github.com/Wenzel/jsonresume-theme-kendall/tree/projects_support)?

**Comment by felipecrs** [comment]
@LinuxBozo I rewrote this PR. If you can read it, please. Thanks!

**Comment by LinuxBozo** [comment]
@felipecrs I'll give it a look and see what I can do when I get a chance.

**Comment by LinuxBozo** [comment]
@felipecrs This is now handled, and published as version 0.2.0 of the theme.

**Comment by felipecrs** [comment]
@LinuxBozo This is awesome! Thank you so much!
