### ISSUE TITLE
Photo is not updated with picture value

### ISSUE THREAD

**Issue by github-throwaway** [LinuxBozo/jsonresume-theme-kendall#38]
The theme does not honor the picture value in the `resume.json`file, instead the `www.gravatar.com/avatar/f425f32f41660c2f475423dfa6112478?s=200&r=pg&d=mm"` is used.

**Comment by paskal** [comment]
According to [code](https://github.com/LinuxBozo/jsonresume-theme-kendall/blob/master/index.js#L48), it honors `basics.image`, not `picture`. That seems to align with [resume.json schema](https://github.com/jsonresume/resume-schema/blob/master/schema.json#L28). Are you sure you are using the right key in the JSON for the image?

**Comment by github-throwaway** [comment]
Yup, that was it. Thanks for pointing it out.
