### ISSUE TITLE
Profile Icons Disappearing

### ISSUE THREAD

**Issue by zainfathoni** [LinuxBozo/jsonresume-theme-kendall#9]
I tried to generate the JSON Resume file using the [Resume Editor](http://registry.jsonresume.org/#kendall) and it works well on the preview page.
![image](https://cloud.githubusercontent.com/assets/6315466/12067579/bc26af02-b02e-11e5-8bf3-e101861802aa.png)

But after downloading the JSON Resume file and building an HTML file based on the JSON file, the **fa fa-twitter-square** class disappeared which cause the icons missing.
![image](https://cloud.githubusercontent.com/assets/6315466/12067435/60231332-b02c-11e5-9358-0ca9377baeb6.png)
![image](https://cloud.githubusercontent.com/assets/6315466/12067582/c9ecde7c-b02e-11e5-84a6-d6c738d0f4bd.png)

I already made sure the JSON file is exactly same with the one in the Resume Editor. I also tried to use both installation (from **npm** and directly from **github**), but the results are the same.
I even tried to modify the source code, but I am still a newbie in Node.js, so I didn't know what I did for sure.

If you manage to fix it later, please let me know where the problem source is exactly. Thank you very much. :smile:

**Comment by xuyizhe** [comment]
I met the same bug when I use [**HackMyResume**](https://github.com/hacksalot/HackMyResume) to build. The problem may come from it if you also use.  [**resume-cli**](https://github.com/jsonresume/resume-cli) can work well.

**Comment by anthu** [comment]
I'm using [FluentCV](https://github.com/fluentdesk/FluentCV) and facing the same issue. I investigated that the network name doesn't match in the switch/case statement.

For example the value "github" in my json is encoded (after using charCodeAt()) "NaN 64 64 64 126 103 105 116 104 117 98 126 64 64 64 64" but should be "103 105 116 104 117 98".

For my case I found a workaround: see anthu@216fbb5

**Comment by LinuxBozo** [comment]
@anthu want to go ahead and submit a pull request for that?

**Comment by anthu** [comment]
I've found the main reason for the failure with FluentCv/HackMyResume. Both tools are hardening the strings against interpretation as Markdown (with '@@@@~' + txt + '~@@@@' ). So the hardened strings of course don't match to plain strings.

I will open a Merge Request to FluentCV- hope to get the reason.

So far - here is my fix for FluentCV: anthu/FluentCV@5f324fd

**Comment by LinuxBozo** [comment]
In that case, closing.. thanks for the investigation work!
